import Head from "next/head";
import {
  Header,
  Banner,
  Footer,
  Howwework,
  Viewourproject,
  Frequentlyaskedquestions,
  Features,
  Whatourclinets,
  Sendinquiry,
  Ourblog,
} from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Howwework />
      <Viewourproject />
      <Features />
      <Whatourclinets />
      <Frequentlyaskedquestions />
      <Sendinquiry />
      <Ourblog />
      <Footer />
    </div>
  );
}
