import Head from "next/head";
import { useState } from "react";
import {
  Header,
  Banner,
  Footer,
  Howwework,
  Viewourproject,
  Features,
  Whatourclinets,
  Sendinquiry,
  Ourblog,
  Bottombar,
  Frequentlyaskedquestions,
  Loader,
} from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [toggleMenu, setToggleMenu] = useState(false);
  const AddLoader = () => {
    setToggleMenu(true);
    setTimeout(() => {
      setToggleMenu(false);
    }, 3000);
  };
  return (
    <div className={styles.container}>
      {toggleMenu && (
        <div
          style={{
            zIndex: 999999999999,
            position: "absolute",
            height: "100vh",
            width: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Loader />
        </div>
      )}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header AboutClick={() => AddLoader()} />
      <Banner />
      <Howwework />
      <Bottombar />
      <Viewourproject />
      <Features />
      <Whatourclinets />
      <Frequentlyaskedquestions />
      <Sendinquiry />
      <Ourblog />
      <Footer />
    </div>
  );
}
